import { CLUB_FIXTURES, getPlayerUpcomingFixtures, bestXI, getSquad, horizonProjection, isLegalTransfer, players as defaultPlayers, transferDecision, transfers, type Player, type Position, type Transfer } from './domain.ts'
import { evaluateSimultaneousTransfers } from './core/transfers.ts'
import { MODEL_VERSION, projectPlayer } from './model.ts'

export type ProvenanceSource = 'official_fpl' | 'local_snapshot' | 'projection_model_v1' | 'deterministic_optimizer' | 'llm_judgement'
export type Evidence<T> = { value:T; source:ProvenanceSource; asOf?:string; note?:string }
export type ToolResponse<T> = { tool:string; data:T; evidence:Evidence<unknown>[] }
export type Horizon = number
export type PlayerFilters = { query?:string; position?:Position; club?:string; maxPrice?:number; minProjection?:number }
export type FixtureFact = { gameweek:number; opponent:string; venue:'H'|'A'; difficulty:number; kickoff?:string }
export type ToolContext = { players:Player[]; squad:Player[]; bank:number; freeTransfers:number; currentGameweek:number|null; fixturesByPlayer?:Record<number,FixtureFact[]>; fixtureRunsByTeam?:Record<string,FixtureFact[]> }

const fact=<T>(value:T,note?:string):Evidence<T>=>({value,source:'official_fpl',note})
const model=<T>(value:T,note?:string):Evidence<T>=>({value,source:'projection_model_v1',note})
const optimizer=<T>(value:T,note?:string):Evidence<T>=>({value,source:'deterministic_optimizer',note})
const playerFact=(p:Player)=>({id:fact(p.id),name:fact(p.name),club:fact(p.club),position:fact(p.position),price:fact(p.price),status:fact(p.minutes<75?'minutes-risk':'available'),ownership:fact(p.ownership),minutes:fact(p.minutes),fixture:fact(p.fixture)})
const defaultContext=():ToolContext=>({players:defaultPlayers,squad:getSquad(),bank:1.2,freeTransfers:1,currentGameweek:1,fixturesByPlayer:Object.fromEntries(defaultPlayers.map(p=>[p.id,getPlayerUpcomingFixtures(p,5)])),fixtureRunsByTeam:CLUB_FIXTURES})

export function createToolContext(input:Partial<ToolContext>={}):ToolContext { return {...defaultContext(),...input} }
export function getMySquad(ctx:ToolContext=createToolContext()):ToolResponse<{players:ReturnType<typeof playerFact>[];bank:Evidence<number>;freeTransfers:Evidence<number>}>{ const data={players:ctx.squad.map(playerFact),bank:fact(ctx.bank),freeTransfers:fact(ctx.freeTransfers)};return {tool:'getMySquad',data,evidence:[fact(ctx.squad.map(p=>p.id),'squad selection'),fact(ctx.bank,'user-entered bank'),fact(ctx.freeTransfers,'user-entered free transfers')]}}
export function getPlayer(playerId:number,ctx:ToolContext=createToolContext()):ToolResponse<{player:ReturnType<typeof playerFact>|null}>{const p=ctx.players.find(x=>x.id===playerId)||null;return {tool:'getPlayer',data:{player:p?playerFact(p):null},evidence:p?[fact(p.id),fact(p.name),fact(p.price),fact(p.minutes)]:[]}}
export function searchPlayers(filters:PlayerFilters={},ctx:ToolContext=createToolContext()):ToolResponse<{players:ReturnType<typeof playerFact>[]}>{const q=filters.query?.toLowerCase();const result=ctx.players.filter(p=>(!q||`${p.name} ${p.club}`.toLowerCase().includes(q))&&(!filters.position||p.position===filters.position)&&(!filters.club||p.club===filters.club)&&(!filters.maxPrice||p.price<=filters.maxPrice)&&(!filters.minProjection||p.projection>=filters.minProjection)).map(playerFact);return {tool:'searchPlayers',data:{players:result},evidence:[fact(filters,'search filters'),fact(result.map(p=>p.id),'official player catalogue')]}}
export function getPlayerFixtures(playerId:number,horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{playerId:number;fixtures:Evidence<FixtureFact[]>}>{const fixtures=(ctx.fixturesByPlayer?.[playerId]||[]).slice(0,horizon);return {tool:'getPlayerFixtures',data:{playerId,fixtures:fact(fixtures,'official fixture feed; empty means not loaded for this player')},evidence:[fact(playerId),fact(fixtures)]}}
export function getPlayerProjection(playerId:number,horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{playerId:number;expectedPoints:Evidence<number>;expectedMinutes:Evidence<number>}>{const p=ctx.players.find(x=>x.id===playerId);if(!p)throw new Error(`Unknown player ${playerId}`);const projection=projectPlayer(p,ctx.currentGameweek||1);const expectedPoints=model(horizonProjection(p,horizon),`${MODEL_VERSION}; horizon=${horizon}`);const expectedMinutes=model(+(projection.expectedMinutes*(horizon===1?1:horizon===3?2.82:4.5)).toFixed(1),`${MODEL_VERSION}; expected minutes scaled across horizon`);return {tool:'getPlayerProjection',data:{playerId,expectedPoints,expectedMinutes},evidence:[expectedPoints,expectedMinutes]}}
export function comparePlayers(playerIds:number[],horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{players:Array<{player:ReturnType<typeof playerFact>;expectedPoints:Evidence<number>;value:Evidence<number>}>}>{const rows=playerIds.map(id=>{const p=ctx.players.find(x=>x.id===id);if(!p)throw new Error(`Unknown player ${id}`);return {player:playerFact(p),expectedPoints:model(horizonProjection(p,horizon)),value:model(+(horizonProjection(p,horizon)/p.price).toFixed(2),'projected points per £m')}});return {tool:'comparePlayers',data:{players:rows},evidence:rows.flatMap(r=>[r.expectedPoints,r.value])}}
export function getBestTransfers(horizon:Horizon,limit=10,ctx:ToolContext=createToolContext()):ToolResponse<{transfers:Transfer[];roll:Evidence<boolean>}>{const ranked=transfers(horizon,ctx.bank,ctx.freeTransfers,ctx.squad,ctx.players).slice(0,limit);const decision=transferDecision(horizon,ctx.bank,ctx.freeTransfers,ctx.squad,ctx.players);return {tool:'getBestTransfers',data:{transfers:ranked,roll:optimizer(decision.roll,decision.reason)},evidence:[optimizer(ranked.map(t=>({out:t.out.id,in:t.in.id,rawGain:t.gain,netGain:t.net}))),optimizer(decision.roll)]}}
export function getBestLineup(gameweek:number,ctx:ToolContext=createToolContext()):ToolResponse<{gameweek:number;lineup:Player[];bench:Player[]}>{const lineup=bestXI(1,ctx.squad);const starters=new Set(lineup.map(p=>p.id));return {tool:'getBestLineup',data:{gameweek,lineup,bench:ctx.squad.filter(p=>!starters.has(p.id)).sort((a,b)=>a.projection-b.projection)},evidence:[optimizer(lineup.map(p=>p.id),'legal formation maximizing next-GW projected points')]}}
export function getCaptainCandidates(gameweek:number,ctx:ToolContext=createToolContext()):ToolResponse<{gameweek:number;candidates:Array<{player:Player;projectedContribution:Evidence<number>}>}>{const lineup=getBestLineup(gameweek,ctx).data.lineup;const score=(p:Player)=>horizonProjection(p,1);const candidates=lineup.sort((a,b)=>score(b)-score(a)).map(p=>({player:p,projectedContribution:model(+(score(p)*2).toFixed(1),'captain multiplier applied')}));return {tool:'getCaptainCandidates',data:{gameweek,candidates},evidence:candidates.map(c=>c.projectedContribution)}}
export function getUpgradeOpportunities(horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{opportunities:Array<{out:Player;replacement:Player|null;gain:Evidence<number>;label:'KEEP'|'UPGRADE OPPORTUNITY'|'ROLL'}>}>{const ranked=transfers(horizon,ctx.bank,ctx.freeTransfers,ctx.squad,ctx.players);const opportunities=ctx.squad.map(out=>{const best=ranked.find(t=>t.out.id===out.id);return {out,replacement:best?.in||null,gain:optimizer(best?.gain||0),label:(best&&best.net>=1?'UPGRADE OPPORTUNITY':'KEEP') as 'UPGRADE OPPORTUNITY'|'KEEP'} });return {tool:'getUpgradeOpportunities',data:{opportunities},evidence:opportunities.map(o=>o.gain)}}
export function simulateTransfer(playerOut:number,playerIn:number,horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{legal:boolean;out:Player|null;in:Player|null;rawGain:Evidence<number>;hitCost:Evidence<number>;netGain:Evidence<number>}>{const out=ctx.squad.find(p=>p.id===playerOut)||null;const incoming=ctx.players.find(p=>p.id===playerIn)||null;if(!out||!incoming)return {tool:'simulateTransfer',data:{legal:false,out,in:incoming,rawGain:optimizer(0),hitCost:optimizer(0),netGain:optimizer(0)},evidence:[]};const legal=isLegalTransfer(ctx.squad,out,incoming,ctx.bank);const rawGain=+(horizonProjection(incoming,horizon)-horizonProjection(out,horizon)).toFixed(1);const hitCost=ctx.freeTransfers>0?0:4;return {tool:'simulateTransfer',data:{legal,out,in:incoming,rawGain:optimizer(rawGain),hitCost:optimizer(hitCost,'FPL hit cost'),netGain:optimizer(legal?rawGain-hitCost:0,'illegal moves are zeroed')},evidence:[fact(out.id),fact(incoming.id),optimizer(legal)]}}
export function simulateTransfers(moveIds:Array<[number,number]>,horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{legal:boolean;netGain:Evidence<number>;moves:unknown[]}>{
  const moves=[] as Array<{out:Player;in:Player}>
  for(const [outId,inId] of moveIds){
    const out=ctx.squad.find(p=>p.id===outId),incoming=ctx.players.find(p=>p.id===inId)
    if(!out||!incoming)return {tool:'simulateTransfers',data:{legal:false,netGain:optimizer(0),moves},evidence:[optimizer(false,'unknown player in transfer route')]}
    moves.push({out,in:incoming})
  }
  const result=evaluateSimultaneousTransfers({
    squad:ctx.squad.map(player=>({id:player.id,club:player.club,position:player.position,active:player.active,purchasePriceTenths:Math.round(player.price*10),sellingPriceTenths:player.sellingPrice===undefined?Math.round(player.price*10):player.sellingPrice===null?null:Math.round(player.sellingPrice*10)})),
    moves:moves.map(move=>({outId:move.out.id,incoming:{id:move.in.id,club:move.in.club,position:move.in.position,active:move.in.active,purchasePriceTenths:Math.round(move.in.price*10),sellingPriceTenths:Math.round(move.in.price*10)}})),
    bankBeforeTenths:Math.round(ctx.bank*10),freeTransfers:ctx.freeTransfers,
  })
  if(result.status!=='LEGAL')return {tool:'simulateTransfers',data:{legal:false,netGain:optimizer(0),moves},evidence:[optimizer(result.status,result.reason)]}
  const total=moves.reduce((sum,move)=>sum+horizonProjection(move.in,horizon)-horizonProjection(move.out,horizon),0)
  return {tool:'simulateTransfers',data:{legal:true,netGain:optimizer(+(total-result.hitCost).toFixed(1)),moves},evidence:[optimizer(total,'raw multi-transfer gain'),optimizer(result.hitCost,'aggregate hit cost'),fact(result.bankAfterTenths,'exact bank after in tenths')]}
}
export function getTeamConstraints(ctx:ToolContext=createToolContext()):ToolResponse<{squadSize:Evidence<number>;bank:Evidence<number>;freeTransfers:Evidence<number>;maxPerClub:Evidence<number>;formation:Evidence<string>}>{return {tool:'getTeamConstraints',data:{squadSize:fact(ctx.squad.length),bank:fact(ctx.bank),freeTransfers:fact(ctx.freeTransfers),maxPerClub:fact(3),formation:fact('1 GK; 3+ DEF; 2+ MID; 1+ FWD')},evidence:[fact(15),fact(ctx.bank),fact(ctx.freeTransfers),fact(3)]}}
export function getRecentMinutes(playerId:number,ctx:ToolContext=createToolContext()):ToolResponse<{playerId:number;minutes:Evidence<number>;sample:Evidence<string>}>{const p=ctx.players.find(x=>x.id===playerId);if(!p)throw new Error(`Unknown player ${playerId}`);const minutes=p.expectedMinutes??p.minutes;return {tool:'getRecentMinutes',data:{playerId,minutes:fact(minutes),sample:fact(p.coldStart?'cold-start estimate; no Premier League history available':'role estimate derived from accrued minutes and availability')},evidence:[fact(minutes)]}}
export function getFixtureRun(teamId:string,horizon:Horizon,ctx:ToolContext=createToolContext()):ToolResponse<{teamId:string;fixtures:Evidence<FixtureFact[]>}>{const fixtures=(ctx.fixtureRunsByTeam?.[teamId]||[]).slice(0,horizon);return {tool:'getFixtureRun',data:{teamId,fixtures:fact(fixtures)},evidence:[fact(fixtures)]}}

export const fplTools={getMySquad,getPlayer,searchPlayers,getPlayerFixtures,getPlayerProjection,comparePlayers,getBestTransfers,getBestLineup,getCaptainCandidates,getUpgradeOpportunities,simulateTransfer,simulateTransfers,getTeamConstraints,getRecentMinutes,getFixtureRun}
export type FplToolName=keyof typeof fplTools
export const fplToolManifest = [
  {name:'getMySquad',description:'Read the current user squad, bank and free transfers.',inputSchema:{type:'object',properties:{}}},
  {name:'getPlayer',description:'Read trusted source facts for one player.',inputSchema:{type:'object',required:['playerId'],properties:{playerId:{type:'integer'}}}},
  {name:'searchPlayers',description:'Search the player catalogue with position, club, price and projection filters.',inputSchema:{type:'object',properties:{query:{type:'string'},position:{type:'string'},club:{type:'string'},maxPrice:{type:'number'},minProjection:{type:'number'}}}},
  {name:'getPlayerFixtures',description:'Read a player fixture run for a selected horizon.',inputSchema:{type:'object',required:['playerId','horizon'],properties:{playerId:{type:'integer'},horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'getPlayerProjection',description:'Read deterministic expected minutes and points.',inputSchema:{type:'object',required:['playerId','horizon'],properties:{playerId:{type:'integer'},horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'comparePlayers',description:'Compare player facts, projections and value.',inputSchema:{type:'object',required:['playerIds','horizon'],properties:{playerIds:{type:'array',items:{type:'integer'}},horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'getBestTransfers',description:'Rank legal transfers by deterministic net gain.',inputSchema:{type:'object',required:['horizon'],properties:{horizon:{type:'integer',enum:[1,3,5]},limit:{type:'integer'}}}},
  {name:'getBestLineup',description:'Calculate a legal projected starting XI and bench.',inputSchema:{type:'object',required:['gameweek'],properties:{gameweek:{type:'integer'}}}},
  {name:'getCaptainCandidates',description:'Rank captain candidates from the legal best XI.',inputSchema:{type:'object',required:['gameweek'],properties:{gameweek:{type:'integer'}}}},
  {name:'getUpgradeOpportunities',description:'Find the weakest owned slots and best realistic upgrades.',inputSchema:{type:'object',required:['horizon'],properties:{horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'simulateTransfer',description:'Check one transfer legality, raw gain, hit cost and net gain.',inputSchema:{type:'object',required:['playerOut','playerIn','horizon'],properties:{playerOut:{type:'integer'},playerIn:{type:'integer'},horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'simulateTransfers',description:'Check a sequence of transfers and aggregate net gain.',inputSchema:{type:'object',required:['transfers','horizon'],properties:{transfers:{type:'array'},horizon:{type:'integer',enum:[1,3,5]}}}},
  {name:'getTeamConstraints',description:'Read budget, free transfers and FPL legality constraints.',inputSchema:{type:'object',properties:{}}},
  {name:'getRecentMinutes',description:'Read the available recent-minutes signal and its sample limitations.',inputSchema:{type:'object',required:['playerId'],properties:{playerId:{type:'integer'}}}},
  {name:'getFixtureRun',description:'Read a club fixture run for a selected horizon.',inputSchema:{type:'object',required:['teamId','horizon'],properties:{teamId:{type:'string'},horizon:{type:'integer',enum:[1,3,5]}}}}
] as const
